apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"order-service","namespace":"semicolon"},"spec":{"ports":[{"name":"http","port":80,"targetPort":8084}],"selector":{"app":"order"},"type":"ClusterIP"}}
  creationTimestamp: "2026-02-17T20:03:45Z"
  name: order-service
  namespace: semicolon
  resourceVersion: "145129"
  uid: c895cf94-f96a-453d-b3da-214996acd37b
spec:
  - 10.43.230.154
  internalTrafficPolicy: Cluster
  - IPv4
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8084
  selector:
    app: order
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
