apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"user-service","namespace":"semicolon"},"spec":{"ports":[{"name":"http","port":80,"targetPort":8082}],"selector":{"app":"user"},"type":"ClusterIP"}}
  creationTimestamp: "2026-02-17T20:03:45Z"
  name: user-service
  namespace: semicolon
  resourceVersion: "145133"
  uid: 17769128-6846-4041-b794-40341bcb8352
spec:
  clusterIP: 10.43.180.39
  clusterIPs:
  - 10.43.180.39
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: user
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
