apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-datasources
  namespace: semicolon
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: PBFA97CFB590B2093
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        jsonData:
          timeInterval: 15s
  log-api.yml: |
    apiVersion: 1
    datasources:
      - name: Log-API
        type: yesoreyeram-infinity-datasource
        uid: PCA84556805E1F3AF
        access: proxy
        url: http://log-consumer-service:9000
        jsonData:
          url: http://log-consumer-service:9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: semicolon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: semicolon-env
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: semicolon-env
                  key: GRAFANA_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: semicolon-env
                  key: GRAFANA_ADMIN_PASSWORD
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Viewer"
            - name: GF_DATE_FORMATS_DEFAULT_TIMEZONE
              value: Asia/Seoul
            - name: GF_INSTALL_PLUGINS
              value: "yesoreyeram-infinity-datasource"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: provisioning-datasources
          configMap:
            name: grafana-provisioning-datasources

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: semicolon
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
