apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-consumer
  namespace: semicolon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-consumer
  template:
    metadata:
      labels:
        app: log-consumer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "9000"
    spec:
      containers:
        - name: log-consumer
          image: ${{ secrets.DOCKER_USERNAME }}/semicolon-log-consumer:latest
          envFrom:
            - secretRef:
                name: semicolon-env
          env:
            - name: MONGO_HOST
              value: "mongodb-service"
            - name: MONGO_PORT
              value: "27017"
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx256m"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9000
            initialDelaySeconds: 40
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: log-consumer-service
  namespace: semicolon
spec:
  selector:
    app: log-consumer
  ports:
    - port: 9000
      targetPort: 9000
