spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  access:
    secret:
      key: ${JWT_ACCESS_SECRET}
  refresh:
    secret:
      key: ${JWT_REFRESH_SECRET}

crypto:
  key: ${CRYPTO_KEY}

custom:
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://localhost:3000}
