apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2026-02-17T20:03:45Z","name":"auth-service","namespace":"semicolon","resourceVersion":"145125","uid":"4293264f-82a7-49bb-b42e-99e8c867a048"},"spec":{"clusterIP":"10.43.35.125","clusterIPs":["10.43.35.125"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8081}],"selector":{"app":"auth"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2026-02-17T20:03:45Z"
  name: auth-service
  namespace: semicolon
  resourceVersion: "160478"
  uid: 4293264f-82a7-49bb-b42e-99e8c867a048
spec:
  clusterIP: 10.43.35.125
  clusterIPs:
  - 10.43.35.125
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: auth
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
