apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"payment-service","namespace":"semicolon"},"spec":{"ports":[{"name":"http","port":80,"targetPort":8086}],"selector":{"app":"payment"},"type":"ClusterIP"}}
  creationTimestamp: "2026-02-18T10:38:33Z"
  name: payment-service
  namespace: semicolon
  resourceVersion: "161059"
  uid: 521b4684-690d-48f8-8db1-8ec23372205f
spec:
  clusterIP: 10.43.7.254
  clusterIPs:
  - 10.43.7.254
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8086
  selector:
    app: payment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
