apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"team05-redpanda","namespace":"semicolon"},"spec":{"ports":[{"name":"kafka","port":9092,"targetPort":9092}]}}
  creationTimestamp: "2026-02-17T17:16:34Z"
  name: team05-redpanda
  namespace: semicolon
  resourceVersion: "140937"
  uid: e6f01e7d-dff0-44cb-9303-394ae7626294
spec:
  clusterIP: 10.43.237.202
  clusterIPs:
  - 10.43.237.202
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: kafka
    port: 9092
    protocol: TCP
    targetPort: 9092
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
