apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon
  namespace: semicolon
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: coupon
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-02-18T05:16:37+09:00"
      labels:
        app: coupon
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: semicolon-env
            - secretRef:
                name: coupon-db
          # Image tag injected by CI
          image: dukku/semicolon-coupon:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: coupon
          ports:
            - containerPort: 8085
              protocol: TCP
          resources:
            limits:
              cpu: 600m
              memory: 768Mi
            requests:
              cpu: 50m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
