apiVersion: v1
kind: Service
metadata:
  name: coupon-service
  namespace: semicolon
spec:
  type: ClusterIP
  selector:
    app: coupon
  ports:
    - name: http
      port: 80
      targetPort: 8085
      protocol: TCP
