description = 'log-consumer'

bootJar { enabled = true }

dependencies {
    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // MongoDB
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'

    // Jackson
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    // Actuator + Prometheus 메트릭
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
