# coupon 서비스의 기본 실행 설정입니다.
server:
  port: 8085

spring:
  config:
    import: classpath:application-common.yml
  application:
    name: coupon

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:coupon_service}?sslmode=${DB_SSLMODE:disable}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
