description = 'ai'

bootJar {
    enabled = true
}


repositories {
    maven { url 'https://repo.spring.io/milestone' }
    maven { url 'https://repo.spring.io/snapshot' }
    maven {
        name = 'Central Portal Snapshots'
        url = 'https://repo.spring.io/snapshots/central-portal'
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

dependencies {

    // ★ 핵심: 공통 모듈 연결 (Web, Security, JPA, JWT, Swagger 등 포함됨)
    implementation project(':common')

    // === DB Drivers (실행 환경에 따라 다를 수 있으므로 서비스별 유지 추천) ===
    runtimeOnly 'org.postgresql:postgresql'
    runtimeOnly 'com.h2database:h2'


    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    // Database
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Spring AI
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'

    // Spring AI Chat Memory & Vector Store
    implementation 'org.springframework.ai:spring-ai-starter-vector-store-pgvector'
    implementation 'org.springframework.ai:spring-ai-advisors-vector-store'
    implementation 'org.springframework.ai:spring-ai-starter-model-chat-memory-repository-jdbc'

    // Hibernate Vector (pgvector support)
    implementation 'org.hibernate.orm:hibernate-vector'
    implementation 'org.springframework.boot:spring-boot-starter-json'


    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'

    // === Test ===
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webflux-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers-postgresql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test) {
    useJUnitPlatform()
}


