apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"semicolon"}}
  creationTimestamp: "2026-02-17T17:02:08Z"
  labels:
    kubernetes.io/metadata.name: semicolon
  name: semicolon
  resourceVersion: "145113"
  uid: 120edd12-29ee-41be-b145-9ad6bd08af75
spec:
  finalizers:
  - kubernetes
