apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  namespace: semicolon
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ai
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-02-23T00:00:00+09:00"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8089"
      labels:
        app: ai
    spec:
      automountServiceAccountToken: false
      containers:
        - envFrom:
            - secretRef:
                name: semicolon-env
          image: dukku/semicolon-ai:latest
          imagePullPolicy: IfNotPresent
          name: ai
          ports:
            - containerPort: 8089
              protocol: TCP
          resources:
            limits:
              cpu: 600m
              memory: 832Mi
            requests:
              cpu: 50m
              memory: 512Mi
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx512m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 150
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8089
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
