apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: semicolon
spec:
  type: ClusterIP
  selector:
    app: ai
  ports:
    - name: http
      port: 80
      targetPort: 8089
      protocol: TCP
