apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: semicolon
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8083
  selector:
    app: product
  sessionAffinity: None
  type: ClusterIP
