apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: semicolon
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
  sessionAffinity: None
